apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui
spec:
  selector:
    app: ecommerce-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
    spec:
      containers:
        - name: ecommerce-ui
          image: yamini8756/ecommerce-ui
          ports:
            - containerPort: 80
